// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrbWeaver.Data;

#nullable disable

namespace OrbWeaver.Data.Migrations
{
    [DbContext(typeof(OrbWeaverDbContext))]
    [Migration("20260104192609_InitWithUpdateLog")]
    partial class InitWithUpdateLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrbWeaver.Data.DataModel.MessageLog", b =>
                {
                    b.Property<string>("Hash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash");

                    b.Property<DateTime>("LoggedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_at")
                        .HasDefaultValueSql("now()");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.HasKey("Hash")
                        .HasName("pk_messages_log");

                    b.ToTable("messages_log", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
