// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrbWeaver.Data;
using OrbWeaver.Infrastructure;

#nullable disable

namespace OrbWeaver.Data.Migrations
{
    [DbContext(typeof(OrbWeaverDbContext))]
    [Migration("20260203201520_MessageLoggingEnhancements")]
    partial class MessageLoggingEnhancements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrbWeaver.Infrastructure.DataModel.AlertData", b =>
                {
                    b.Property<Guid>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("alert_id");

                    b.Property<string>("Expression")
                        .IsRequired()
                        .HasColumnType("jsonpath")
                        .HasColumnName("expression");

                    b.Property<string>("Filter")
                        .IsRequired()
                        .HasColumnType("jsonpath")
                        .HasColumnName("filter");

                    b.Property<DateTime>("LastHandledTs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_handled_ts")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("AlertId")
                        .HasName("pk_alerts");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("OrbWeaver.Infrastructure.DataModel.MessageLog", b =>
                {
                    b.Property<string>("Hash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash");

                    b.Property<DateTime>("LoggedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_at")
                        .HasDefaultValueSql("now()");

                    b.Property<JsonDocument>("Payload")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Hash")
                        .HasName("pk_messages_log");

                    b.HasIndex("Payload")
                        .HasDatabaseName("ix_messages_log_payload");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Payload"), "gin");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_messages_log_timestamp");

                    b.ToTable("messages_log", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
